name: gsf
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - asdf
  - astropy
  - corner
  - emcee
  - lmfit
  - matplotlib-base
  - numpy
  - pandas
  - pip
  - python=3.9
  - scipy
  - setuptools
  - uncertainties
  - pip:
    - git+https://github.com/dfm/python-fsps.git
    - git+https://github.com/mtakahiro/gsf.git

